ccollections
defaultdict
p0
(c__builtin__
list
p1
tp2
Rp3
(Vconfirmar
p4
Vconceito:Deus
p5
Vconceito:atributo
p6
Vconceito:homem
p7
Vconceito:ideia
p8
tp9
(lp10
V13. Quando dizemos que Deus é eterno, infinito, imutável, imaterial, único, onipotente, soberanamente justo e bom, temos ideia completa de seus atributos? Do vosso ponto de vista, sim, porque credes abranger tudo. Sabei, porém, que há coisas que estão acima da inteligência do homem mais inteligente, as quais a vossa linguagem, restrita às vossas ideias e sensações, não tem meios de exprimir. 2 A razão, com efeito, vos diz que Deus deve possuir em grau supremo essas perfeições, porquanto, se uma lhe faltasse, ou não fosse infinita, já ele não seria superior a tudo, não seria, por conseguinte, Deus. 3 Para estar acima de todas as coisas, Deus tem que se achar isento de qualquer vicissitude e de qualquer das imperfeições que a imaginação possa conceber.
p11
as(g4
Vconceito:Deus
p12
Vqualidade:distinto
p13
tp14
(lp15
V14. Deus é um ser distinto, ou será, como opinam alguns, a resultante de todas as forças e de todas as inteligências do Universo reunidas? Se fosse assim, Deus não existiria, porquanto seria efeito e não causa. Ele não pode ser ao mesmo tempo uma e outra coisa
p16
as(g4
Vacaso
p17
Vcausa_primaria
p18
tp19
(lp20
V8. Que se deve pensar da opinião dos que atribuem a formação primária a uma combinação fortuita da matéria, ou, por outra, ao acaso? Outro absurdo! Que homem de bom senso pode considerar o acaso um ser inteligente? E, demais, que é o acaso? Nada.
p21
as(g4
Vacaso
p22
Vconceito:tudo
p23
tp24
(lp25
g21
as(Vdefinir
p26
Vconceito:panteismo
p27
tp28
(lp29
V15. Que se deve pensar da opinião segundo a qual todos os corpos da Natureza, todos os seres, todos os globos do Universo seriam partes da Divindade e constituiriam, em conjunto, a própria Divindade, ou, por outra, que se deve pensar da doutrina panteísta? Não podendo fazer-se Deus, o homem quer ao menos ser uma parte de Deus.
p30
as(g26
Vcampo:existir
p31
Vcampo:sentir
p32
Vconceito:Deus
p33
tp34
(lp35
V5. Que dedução se pode tirar do sentimento instintivo, que todos os homens trazem em si, da existência de Deus? A de que Deus existe; pois, donde lhes viria esse sentimento, se não tivesse uma base? É ainda uma consequência do princípio \u2014 não há efeito sem causa.
p36
as(g26
Vconceito:infinito
p37
tp38
(lp39
V2. Que se deve entender por infinito? O que não tem começo nem fim: o desconhecido; tudo o que é desconhecido é infinito.
p40
as(g26
Vcausa_primaria
p41
Vinteligencia_divina
p42
tp43
(lp44
V9. Em que é que, na causa primária, se revela uma inteligência suprema e superior a todas as inteligências? Tendes um provérbio que diz: Pela obra se reconhece o autor. Pois bem! Vede a obra e procurai o autor. O orgulho é que gera a incredulidade. O homem orgulhoso nada admite acima de si. Por isso é que ele se denomina a si mesmo de espírito forte. Pobre ser, que um sopro de Deus pode abater!
p45
as(g4
Vconceito:Deus
p46
Vconceito:infinito
p47
tp48
(lp49
V3. Poder-se-ia dizer que Deus é o infinito? Definição incompleta. Pobreza da linguagem humana, insuficiente para definir o que está acima da linguagem dos homens.
p50
as(g4
Vcampo:educar
p51
Vcampo:existir
p52
Vcampo:sentir
p53
Vconceito:Deus
p54
tp55
(lp56
V6. O sentimento íntimo que temos da existência de Deus não poderia ser fruto da educação, resultado de ideias adquiridas? Se assim fosse, porque existiria nos vossos selvagens esse sentimento?
p57
as(g4
Vconceito:Deus
p58
Vconceito:atributo
p59
Vconceito:ideia
p60
tp61
(lp62
g11
as(g26
Vconceito:Deus
p63
tp64
(lp65
V1. Que é Deus? Deus é a inteligência suprema, causa primária de todas as coisas.
p66
as(g4
Vcampo:compreender
p67
Vconceito:Deus
p68
Vconceito:ideia
p69
tp70
(lp71
V12. Embora não possamos compreender a natureza íntima de Deus, podemos formar ideia de algumas de suas perfeições? De algumas, sim. O homem as compreende melhor à proporção que se eleva acima da matéria. Entreve-as pelo pensamento.
p72
as(g26
Vcausa_primaria
p73
tp74
(lp75
g66
as(g4
Vcampo:compreender
p76
Vconceito:Deus
p77
Vconceito:homem
p78
tp79
(lp80
V10. Pode o homem compreender a natureza íntima de Deus? Não; falta-lhe para isso o sentido.
p81
aV11. Será dado um dia ao homem compreender o mistério da Divindade? Quando não mais tiver o espírito obscurecido pela matéria. Quando, pela sua perfeição, se houver aproximado de Deus, ele o verá e compreenderá.
p82
as(g4
Vcampo:compreender
p83
Vconceito:Deus
p84
tp85
(lp86
g81
ag82
as(g4
Vcausa_primaria
p87
Vconceito:materia
p88
tp89
(lp90
V7. Poder-se-ia achar nas propriedades íntimas da matéria a causa primária da formação das coisas? Mas, então, qual seria a causa dessas propriedades? É indispensável sempre uma causa primária.
p91
as(g26
Vcampo:existir
p92
Vcampo:provar
p93
Vconceito:Deus
p94
tp95
(lp96
V4. Onde se pode encontrar a prova da existência de Deus? Num axioma que aplicais às vossas ciências. Não há efeito sem causa. Procurai a causa de tudo o que não é obra do homem e a vossa razão responderá.
p97
as(g26
Vconceito:Deus
p98
Vconceito:Deus
p99
Vconceito:panteismo
p100
Vconceito:parte
p101
tp102
(lp103
g30
as(g4
Vcampo:compreender
p104
Vconceito:Deus
p105
Vconceito:homem
p106
Vconceito:ideia
p107
tp108
(lp109
g72
as(g26
Vconceito:Deus
p110
Vconceito:parte
p111
tp112
(lp113
g30
as(g4
Vcampo:combinar
p114
Vconceito:Deus
p115
tp116
(lp117
g16
as(g4
Vcampo:educar
p118
Vcampo:existir
p119
Vconceito:Deus
p120
tp121
(lp122
g57
as(g26
Vcampo:opor
p123
Vconceito:panteismo
p124
tp125
(lp126
V16. Pretendem os que professam esta doutrina achar nela a demonstração de alguns dos atributos de Deus: Sendo infinitos os mundos, Deus é, por isso mesmo, infinito; não havendo o vazio, ou o nada em parte alguma, Deus está por toda parte; estando Deus em toda parte, pois que tudo é parte integrante de Deus, ele dá a todos os fenômenos da Natureza uma razão de ser inteligente. Que se pode opor a este raciocínio? A razão. Refleti maduramente e não vos será difícil reconhecer-lhe o absurdo.
p127
as(g26
Vinteligencia_divina
p128
tp129
(lp130
g45
as(g4
Vconceito:Deus
p131
Vconceito:ideia
p132
tp133
(lp134
g72
as(g4
Vcampo:combinar
p135
Vcampo:combinar
p136
Vconceito:Deus
p137
Vconceito:forca
p138
Vconceito:inteligencia
p139
Vconceito:tudo
p140
Vqualidade:distinto
p141
tp142
(lp143
g16
as.